identifier: com.danielc0603.immersiveartbg
name: Immersive Art BG
description: Blurred album art as immersive background
version: 1.4.1
author: Daniel
repo: https://github.com/danielc0603/immersive-art-bg
main: plugin.js
icon: icon.png
